---
title: "anova_merge"
author: "Xinyi Xu"
date: "2/8/2021"
output: html_document
---
```{r}
remove.packages("data.table")
install.packages("data.table", type = "source",
    repos = "https://Rdatatable.gitlab.io/data.table")
install.packages("lme4")
install.packages("Matrix")
install.packages("stargazer")
install.packages("coxme")
install.packages("survival")
install.packages("bdsmatrix")
install.packages("ez")
install.packages('xlsx')
install.packages('multcomp')
install.packages('lsmeans')
library(lsmeans)
require(data.table)
require(readxl)
require(lme4)
require(stargazer)
require(coxme)
require(ez)
require(multcomp)
library(afex)
```

```{r}
dt <- read_excel("merged_iat_all.xlsx")
dt=data.frame(dt)
dt[dt['subj_idx']<134,'group']=1
dt[dt['subj_idx']>=134,'group']=2
dt <- data.table(dt)
dt <- within(dt, {
  subj_idx <- as.factor(subj_idx)
  rt <- as.numeric(rt)
  block <- as.numeric(block)
  stim3 <- as.factor(stim3)
  stim4 <- as.factor(stim4)
  condition <- as.factor(condition)
  error <- as.factor(error)
  group <- as.factor(group)
})
```

```{r}

data1 <- droplevels(dt[subj_idx!=106])
data1 <- droplevels(data1[(stim3=='ev1')|(stim3=='ev2')])
data1 <- droplevels(data1[error == 0])
data1 <- droplevels(data1[rt<5000])
data1=subset(data1,block==4|block==7)

```

```{r}

a1=aov_ez(dv = 'rt', id ='subj_idx',data1,between='group',within=c('condition','stim3'))
a1
ls1=lsmeans(a1, c("condition"),by='group')
ls1
update(pairs(ls1), by=NULL, adjust = 'tukey')
pairs(update(pairs(ls1), by=NULL))
pic=lsmip(a1, condition ~group )
pic
```



```{r}
library(dplyr)
data1=data.table(data1)
sum=data1 %>% group_by(subj_idx,condition,group) %>% 
                    summarise(rt_sd=sd(rt)) %>%
                    arrange(condition) %>%
                    ungroup() %>% 
                    group_by(condition,group) %>% 
                    summarise(rt_sd=sd(rt_sd)) %>%
                    arrange(condition,group) %>%
                    ungroup() 
sum
```
```{r}
mean=data1 %>% group_by(subj_idx,condition,group) %>% 
                    summarise(rt_mean=mean(rt)) %>%
                    arrange(condition) %>%
                    ungroup() %>% 
                    group_by(condition,group) %>% 
                    summarise(rt_mean=mean(rt_mean)) %>%
                    arrange(condition,group) %>%
                    ungroup() 
mean
```


